server:
  port: 8085

spring:
  application:
    name: wedding-invitation
  datasource:
    url: jdbc:postgresql://localhost:5432/wedding
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
          hibernate:
            default_schema: wedding
  mail:
    host: smtp.your-provider.com
    port: 587
    username: username
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  cloud:
    aws:
      sqs:
        region: eu-north-1

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  from: ${TWILIO_FROM_NUMBER}


logging:
  level:
    org.springframework.security: INFO

aws:
  sms:
    region: eu-north-1
    origination-identity: ${AWS_SMS_ORIGINATION_IDENTITY:}
    configuration-set-name: ${AWS_SMS_CONFIGURATION_SET_NAME:}
    max-price: ${AWS_SMS_MAX_PRICE:0.20}

app:
  mail:
    from: "Wedding <no-reply@wedding.site.com>"
    domain: "wedding.site.com" #TODO: where should I set it?
    confirmExpiresIn: "48 hours"
    confirmExpiresInHours: 48
